name: CI with Email Alert

on:
  push:
    branches: # Workflow này sẽ được kích hoạt khi có một commit được push lên nhánh main.
      - main

jobs: # định nghĩa job sẽ thực hiện
  build: # đặt tên job
    runs-on: ubuntu-latest # hệ điều hành job được chạy
    steps: # Các bước cụ thể mà job sẽ thực hiện
      - run: echo "hello" # Chạy một lệnh shell (cli)
      - run: ls
      - run: curl https://apistore.cybersoft.edu.vn/api/Produc  



  notify:
    runs-on: ubuntu-latest
    if: failure() # Chạy khi job `build` thất bại
    needs: build

    steps:
      - name: Send warning email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Ví dụ Gmail
          server_port: 465
          username: 'sangrom2003@gmail.com' # Tên đăng nhập email
          password: 'ormcjkndvveervwa' # Mật khẩu app password
          subject: 'CI Build Failed!'
          body: 'The CI build has failed. Check the logs for more details.'
          to: 'khaitruong2112@gmail.com' # Địa chỉ nhận cảnh báo
          from: 'sangrom2003@gmail.com'  # Địa chỉ gửi cảnh báo
