name: Deploy to VPS

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test SSH connection
      run: |
        ssh -v -i ${{ secrets.VPS_KEY }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} exit
 # Để workflow không dừng ngay lập tức nếu có lỗi xảy ra
