name: Deploy
on: 
  push:
    branches:
      - main
jobs:
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Deploy to VPS
  #     uses: appleboy/ssh-action@v1.0.3
  #     with:
  #       host: ${{ secrets.VPS_HOST }}
  #       username: ${{ secrets.VPS_USER }}
  #       key: ${{ secrets.VPS_KEY }}
  #       script: |
  #         cd /root/docker
  #         git pull
  #         docker-compose down
  #         docker-compose build
  #         docker-compose up -d
  #         docker images -f "dangling=true" -q | xargs docker rmi

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl http://152.42.238.114:8888/cicd















  # notify:
  #   runs-on: ubuntu-latest
  #   if: failure() # Chạy khi job `build` thất bại
  #   needs: build 

  #   steps:
  #     - name: Send warning email
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com # Ví dụ Gmail
  #         server_port: 465
  #         username: 'sangrom2003@gmail.com' # Tên đăng nhập email
  #         password: 'ormcjkndvveervwa' # Mật khẩu app password
  #         subject: 'CI Build Failed!'
  #         body: 'The CI build has failed. Check the logs for more details.'
  #         to: 'khaitruong2112@gmail.com' # Địa chỉ nhận cảnh báo
  #         from: 'sangrom2003@gmail.com'  # Địa chỉ gửi cảnh báo
