name: Deploy to VPS

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Verify all secrets are set
      run: |
        if [ -z "${{ secrets.VPS_HOST }}" ]; then
          echo "Error: VPS_HOST is not set!"
          exit 1
        fi
        if [ -z "${{ secrets.VPS_USER }}" ]; then
          echo "Error: VPS_USER is not set!"
          exit 1
        fi
        if [ -z "${{ secrets.VPS_KEY }}" ]; then
          echo "Error: VPS_KEY is not set!"
          exit 1
        fi
        echo "All required secrets are set."

