name: Deploy
on: 
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Deploy to VPS
      uses: webfactory/ssh-agent@v0.9.0
      with:
        host: ${{ secrets.VPS_HOST }}    
        username: ${{ secrets.VPS_USER }}  
        key: ${{ secrets.VPS_KEY }}        
        passphrase: ${{ secrets.VPS_PASSPHRASE }} 
        script:
          cd /root/app/docker
          git pull
          docker-compose down
          docker-compose build
          docker-compose up -d