name: Deploy
on: 
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ vars.VPS_HOST }}    
        username: ${{ vars.VPS_USER }}  
        key: ${{ vars.VPS_KEY }}   
        script: |
          cd /root/app/docker
          git pull
          docker-compose down
          docker-compose build
          docker-compose up -d